name: hackamoon
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.1
  gradient_widgets: ^0.5.0
  rflutter_alert: ^1.0.3
  flip_card: ^0.4.1
  flare_splash_screen: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/image_team.jpg
    - assets/indiana.jpg
    - assets/kaori.jpg
    - assets/batman.jpg
    - assets/shrek.jpg
    - assets/et.jpg

  fonts:
    - family: CaviarDreams
      fonts:
        - asset: assets/CaviarDreams.ttf
        - asset: assets/CaviarDreams_Italic.ttf
          style: italic
    - family: CaviarDreamsBold
      fonts:
        - asset: assets/Caviar_Dreams_Bold.ttf
          weight: 700
