
class TextData{
  String schedule = '1.  Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
  'Donec neque magna, dictum in semper nec, commodo tristique dolor.'
  'Pellentesque hendrerit quam ipsum, at efficitur augue cursus non.'
  'Aenean vestibulum porttitor vestibulum.'
  'Ut venenatis sodales lorem a accumsan.'
  'Cras at auctor augue. Praesent vel aliquam tellus, a ultrices libero.'
  'Aliquam maximus, neque sed rutrum auctor, tellus tortor scelerisque lectus,'
  'non lacinia mauris ante nec diam. Proin consequat, quam a bibendum ultrices,'
  'ex eros tincidunt ligula, sit amet euismod dui mi in sem. '
  'Ut non nisi eu nulla dictum tincidunt. Maecenas eget tempor ex,'
  'sed efficitur massa. Proin luctus consectetur consectetur. '
  'Morbi lectus leo, malesuada eu velit sed, posuere fringilla arcu. '
  'Praesent scelerisque, turpis sed pellentesque dapibus,'
  'lorem mauris tristique nisi, sit amet porttitor nunc orci sit amet justo. '
  'Pellentesque commodo commodo maximus.'
  'Nam nulla sapien, hendrerit id vestibulum in, lobortis vitae sem.'
  'Etiam eget erat id arcu tristique faucibus a non libero. Praesent venenatis'
  'lorem vel tristique suscipit. Quisque nec elit magna.\n\n2.  Nunc ac elementum orci.'
  'Duis sagittis egestas imperdiet. Donec ultrices, eros a scelerisque consequat,'
  'tortor dui tristique lorem, ac gravida erat neque ut nisl. Sed tortor elit,'
  'tincidunt vitae varius sed, fringilla nec leo. Donec gravida eu urna in '
  'elementum. Suspendisse eget diam volutpat, lobortis elit in, malesuada neque.'
  'Quisque quam massa, euismod ut enim et, sagittis ornare ligula.'
  'Curabitur a metus eget massa dignissim cursus at sed leo.'
  'Aenean ante lectus, interdum a finibus at, ornare sit amet dolor.'
  'Nam suscipit euismod elementum. Curabitur scelerisque id erat sit amet '
  'vulputate. Pellentesque elementum laoreet mattis. Morbi non orci neque.'
  'Maecenas vitae lobortis massa. Donec dictum odio dui,'
  ' at viverra erat viverra vel.'
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
  'Donec neque magna, dictum in semper nec, commodo tristique dolor.'
  'Pellentesque hendrerit quam ipsum, at efficitur augue cursus non.'
  'Aenean vestibulum porttitor vestibulum.'
  'Ut venenatis sodales lorem a accumsan.\n\n3.  '
  'Cras at auctor augue. Praesent vel aliquam tellus, a ultrices libero.'
  'Aliquam maximus, neque sed rutrum auctor, tellus tortor scelerisque lectus,'
  'non lacinia mauris ante nec diam. Proin consequat, quam a bibendum ultrices,'
  'ex eros tincidunt ligula, sit amet euismod dui mi in sem. '
  'Ut non nisi eu nulla dictum tincidunt. Maecenas eget tempor ex,'
  'sed efficitur massa. Proin luctus consectetur consectetur. '
  'Morbi lectus leo, malesuada eu velit sed, posuere fringilla arcu. '
  'Praesent scelerisque, turpis sed pellentesque dapibus,'
  'lorem mauris tristique nisi, sit amet porttitor nunc orci sit amet justo. '
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
  'Donec neque magna, dictum in semper nec, commodo tristique dolor.'
  'Pellentesque hendrerit quam ipsum, at efficitur augue cursus non.'
  'Aenean vestibulum porttitor vestibulum.'
  'Ut venenatis sodales lorem a accumsan.'
  'Cras at auctor augue. Praesent vel aliquam tellus, a ultrices libero.'
  'Aliquam maximus, neque sed rutrum auctor, tellus tortor scelerisque lectus,'
  'non lacinia mauris ante nec diam. Proin consequat, quam a bibendum ultrices,'
  'ex eros tincidunt ligula, sit amet euismod dui mi in sem. '
  'Ut non nisi eu nulla dictum tincidunt. Maecenas eget tempor ex,'
  'sed efficitur massa. Proin luctus consectetur consectetur. '
  'Morbi lectus leo, malesuada eu velit sed, posuere fringilla arcu. '
  'Praesent scelerisque, turpis sed pellentesque dapibus,'
  'lorem mauris tristique nisi, sit amet porttitor nunc orci sit amet justo. '
  'Pellentesque commodo commodo maximus.'
  'Nam nulla sapien, hendrerit id vestibulum in, lobortis vitae sem.'
  'Etiam eget erat id arcu tristique faucibus a non libero. Praesent venenatis'
  'lorem vel tristique suscipit. Quisque nec elit magna. Nunc ac elementum orci.'
  'Duis sagittis egestas imperdiet. Donec ultrices, eros a scelerisque consequat,'
  'tortor dui tristique lorem, ac gravida erat neque ut nisl. Sed tortor elit,'
  'tincidunt vitae varius sed, fringilla nec leo. Donec gravida eu urna in '
  'elementum. Suspendisse eget diam volutpat, lobortis elit in, malesuada neque.'
  'Quisque quam massa, euismod ut enim et, sagittis ornare ligula.'
  'Curabitur a metus eget massa dignissim cursus at sed leo.'
  'Aenean ante lectus, interdum a finibus at, ornare sit amet dolor.'
  'Nam suscipit euismod elementum. Curabitur scelerisque id erat sit amet '
  'vulputate. Pellentesque elementum laoreet mattis. Morbi non orci neque.'
  'Maecenas vitae lobortis massa. Donec dictum odio dui,'
  '\n\n4.  at viverra erat viverra vel.'
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
  'Donec neque magna, dictum in semper nec, commodo tristique dolor.'
  'Pellentesque hendrerit quam ipsum, at efficitur augue cursus non.'
  'Aenean vestibulum porttitor vestibulum.'
  'Ut venenatis sodales lorem a accumsan.'
  'Cras at auctor augue. Praesent vel aliquam tellus, a ultrices libero.'
  'Aliquam maximus, neque sed rutrum auctor, tellus tortor scelerisque lectus,'
  'non lacinia mauris ante nec diam. Proin consequat, quam a bibendum ultrices,'
  'ex eros tincidunt ligula, sit amet euismod dui mi in sem. '
  'Ut non nisi eu nulla dictum tincidunt. Maecenas eget tempor ex,'
  'sed efficitur massa. Proin luctus consectetur consectetur. '
  'Morbi lectus leo, malesuada eu velit sed, posuere fringilla arcu. '
  'Praesent scelerisque, turpis sed pellentesque dapibus,'
  'lorem mauris tristique nisi, sit amet porttitor nunc orci sit amet justo. ';
}